# Generated by Django 4.1 on 2022-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisterform',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
