# Generated by Django 4.1 on 2022-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventregisterform_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisterform',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='eventregisterform',
            name='amount',
            field=models.CharField(max_length=111),
        ),
    ]
