# Generated by Django 4.1 on 2022-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventregisterform_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisterform',
            name='amount',
            field=models.CharField(max_length=11111),
        ),
    ]
